apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert
  namespace: example
spec:
  groups:
  - name: Example appp rules 
    rules:
    - alert: Example rule 1
      annotations:
        message: This is just an example
      expr: version{job="prometheus-example-app"} == 1
      for: 1m
      labels:
        severity: warning
 
